export const CARDS = [
  { id: 1, name: "Knight", rarity: "Common", type: "Troop" },
  { id: 2, name: "Archers", rarity: "Common", type: "Troop" },
  { id: 3, name: "Bomber", rarity: "Common", type: "Troop" },
  { id: 4, name: "Goblins", rarity: "Common", type: "Troop" },
  { id: 5, name: "Giant", rarity: "Rare", type: "Troop" },
  { id: 6, name: "P.E.K.K.A", rarity: "Epic", type: "Troop" },
  { id: 7, name: "Minions", rarity: "Common", type: "Troop" },
  { id: 8, name: "Balloon", rarity: "Epic", type: "Troop" },
  { id: 9, name: "Witch", rarity: "Epic", type: "Troop" },
  { id: 10, name: "Barbarians", rarity: "Common", type: "Troop" },
  { id: 11, name: "Golem", rarity: "Epic", type: "Troop" },
  { id: 12, name: "Skeleton Army", rarity: "Epic", type: "Troop" },
  { id: 13, name: "Minion Horde", rarity: "Common", type: "Troop" },
  { id: 14, name: "Valkyrie", rarity: "Rare", type: "Troop" },
  { id: 15, name: "Hog Rider", rarity: "Rare", type: "Troop" },
  { id: 16, name: "Musketeer", rarity: "Rare", type: "Troop" },
  { id: 17, name: "Mini P.E.K.K.A", rarity: "Rare", type: "Troop" },
  { id: 18, name: "Spear Goblins", rarity: "Common", type: "Troop" },
  { id: 19, name: "Giant Skeleton", rarity: "Epic", type: "Troop" },
  { id: 20, name: "Prince", rarity: "Epic", type: "Troop" },
  { id: 21, name: "Fireball", rarity: "Rare", type: "Spell" },
  { id: 22, name: "Arrows", rarity: "Common", type: "Spell" },
  { id: 23, name: "Lightning", rarity: "Epic", type: "Spell" },
  { id: 24, name: "Goblin Barrel", rarity: "Epic", type: "Spell" },
  { id: 25, name: "Freeze", rarity: "Epic", type: "Spell" },
  { id: 26, name: "Mirror", rarity: "Epic", type: "Spell" },
  { id: 27, name: "Rocket", rarity: "Rare", type: "Spell" },
  { id: 28, name: "Rage", rarity: "Epic", type: "Spell" },
  { id: 29, name: "Zap", rarity: "Common", type: "Spell" },
  { id: 30, name: "Poison", rarity: "Epic", type: "Spell" },
  { id: 31, name: "Earthquake", rarity: "Rare", type: "Spell" },
  { id: 32, name: "Clone", rarity: "Epic", type: "Spell" },
  { id: 33, name: "Tornado", rarity: "Epic", type: "Spell" },
  { id: 34, name: "Graveyard", rarity: "Legendary", type: "Spell" },
  { id: 35, name: "Barbarian Barrel", rarity: "Epic", type: "Spell" },
  { id: 36, name: "Bomb Tower", rarity: "Rare", type: "Building" },
  { id: 37, name: "Inferno Tower", rarity: "Rare", type: "Building" },
  { id: 38, name: "Cannon", rarity: "Common", type: "Building" },
  { id: 39, name: "Tesla", rarity: "Common", type: "Building" },
  { id: 40, name: "Mortar", rarity: "Common", type: "Building" },
  { id: 41, name: "X-Bow", rarity: "Epic", type: "Building" },
  { id: 42, name: "Goblin Hut", rarity: "Rare", type: "Building" },
  { id: 43, name: "Barbarian Hut", rarity: "Rare", type: "Building" },
  { id: 44, name: "Furnace", rarity: "Rare", type: "Building" },
  { id: 45, name: "Elixir Collector", rarity: "Rare", type: "Building" },
  { id: 46, name: "Skeleton Barrel", rarity: "Common", type: "Troop" },
  { id: 47, name: "Royal Giant", rarity: "Common", type: "Troop" },
  { id: 48, name: "Three Musketeers", rarity: "Rare", type: "Troop" },
  { id: 49, name: "Lava Hound", rarity: "Legendary", type: "Troop" },
  { id: 50, name: "Ice Wizard", rarity: "Legendary", type: "Troop" },
  { id: 51, name: "Sparky", rarity: "Legendary", type: "Troop" },
  { id: 52, name: "Miner", rarity: "Legendary", type: "Troop" },
  { id: 53, name: "Princess", rarity: "Legendary", type: "Troop" },
  { id: 54, name: "Dark Prince", rarity: "Epic", type: "Troop" },
  { id: 55, name: "Executioner", rarity: "Epic", type: "Troop" },
  { id: 56, name: "Electro Wizard", rarity: "Legendary", type: "Troop" },
  { id: 57, name: "Night Witch", rarity: "Legendary", type: "Troop" },
  { id: 58, name: "Bats", rarity: "Common", type: "Troop" },
  { id: 59, name: "Goblin Gang", rarity: "Common", type: "Troop" },
  { id: 60, name: "Bandit", rarity: "Legendary", type: "Troop" },
  { id: 61, name: "Royal Recruits", rarity: "Common", type: "Troop" },
  { id: 62, name: "Flying Machine", rarity: "Rare", type: "Troop" },
  { id: 63, name: "Mega Knight", rarity: "Legendary", type: "Troop" },
  { id: 64, name: "Skeleton Dragons", rarity: "Rare", type: "Troop" },
  { id: 65, name: "Magic Archer", rarity: "Legendary", type: "Troop" },
  { id: 66, name: "Electro Dragon", rarity: "Epic", type: "Troop" },
  { id: 67, name: "Ghost", rarity: "Legendary", type: "Troop" },
  { id: 68, name: "Ram Rider", rarity: "Legendary", type: "Troop" },
  { id: 69, name: "Zappies", rarity: "Rare", type: "Troop" },
  { id: 70, name: "Rascals", rarity: "Common", type: "Troop" },
  { id: 71, name: "Cannon Cart", rarity: "Epic", type: "Troop" },
  { id: 72, name: "Mega Minion", rarity: "Rare", type: "Troop" },
  { id: 73, name: "Inferno Dragon", rarity: "Legendary", type: "Troop" },
  { id: 74, name: "Heal Spirit", rarity: "Rare", type: "Troop" },
  { id: 75, name: "Ice Spirit", rarity: "Common", type: "Troop" },
  { id: 76, name: "Fire Spirit", rarity: "Common", type: "Troop" },
  { id: 77, name: "Guards", rarity: "Epic", type: "Troop" },
  { id: 78, name: "Royal Ghost", rarity: "Legendary", type: "Troop" },
  { id: 79, name: "Battle Healer", rarity: "Rare", type: "Troop" },
  { id: 80, name: "Goblin Rider", rarity: "Epic", type: "Troop" },
  { id: 81, name: "Electro Spirit", rarity: "Common", type: "Troop" },
  { id: 82, name: "Elixir Golem", rarity: "Rare", type: "Troop" },
  { id: 83, name: "Mother Witch", rarity: "Legendary", type: "Troop" },
  { id: 84, name: "Mighty Miner", rarity: "Champion", type: "Troop" },
  { id: 85, name: "Skeleton King", rarity: "Champion", type: "Troop" },
  { id: 86, name: "Archer Queen", rarity: "Champion", type: "Troop" },
  { id: 87, name: "Golden Knight", rarity: "Champion", type: "Troop" },
  { id: 88, name: "Monk", rarity: "Champion", type: "Troop" },
  { id: 89, name: "Little Prince", rarity: "Champion", type: "Troop" },
  { id: 90, name: "Goblin Demolisher", rarity: "Rare", type: "Troop" },
  { id: 91, name: "Barbarian Party", rarity: "Rare", type: "Troop" },
  { id: 92, name: "Super Witch", rarity: "Legendary", type: "Troop" },
  { id: 93, name: "Lava Golem", rarity: "Epic", type: "Troop" },
  { id: 94, name: "Spirit Barrel", rarity: "Common", type: "Troop" },
  { id: 95, name: "Rocket Artillery", rarity: "Legendary", type: "Building" },
  { id: 96, name: "Wall Breakers", rarity: "Epic", type: "Troop" },
  { id: 97, name: "Skeleton Army", rarity: "Epic", type: "Troop" },
  { id: 98, name: "Super Valkyrie", rarity: "Legendary", type: "Troop" },
];

export const randomCard = () => CARDS[Math.floor(Math.random() * CARDS.length)];
